### PR TITLE
cohort 4: [todo] clarified todo workshop

### PR DESCRIPTION
**Pull request by jonleung**

### CODE REVIEW

**Comment by jonleung** [comment]
The test failed for something completely orthogonal to what I'm working on, not sure how that happened.

**Comment by maxwofford** [comment]
@jonleung What is orthogonal?

**Comment by ssun098** [comment]
http://lmgtfy.com/?q=what+is+orthogonal+

**Comment by maxwofford** [comment]
Merging this because the failed build is in an unlinked reference to `zip-zap-zip`.

**Comment by zachlatta** [comment]
That failed build was odd. I submitted #478 with @MaxWofford to resolve the issue.

**Pull request merged**
