### PR TITLE
Create index of workshops

### PR DESCRIPTION
**Pull request by zachlatta**
@MaxWofford can you review/merge this when you have a chance?

### CODE REVIEW

**Comment by maxwofford** [comment]
@zachlatta I like this format. What if we removed the individual project links in `playbook/ACTIVITIES.md`, and replaced it with a link to this?

**Comment by zachlatta** [comment]
Hmm, we'll need facilitation guidelines in `ACTIVITIES.md` as well. I'm partial towards having both.

Perhaps we should link to the facilitation guidelines in this index as well?

**Comment by maxwofford** [comment]
@zachlatta hmmmmm :/ That's lots of work when we add a new workshop.

**Comment by zachlatta** [comment]
It is, but I think it'd contribute to the overall UX of this playbook. It allows the readers to check out the workshops directory and immediately understand which ones exist and see how to facilitate each one. It also allows them to start from the schedule.

**Pull request merged**
