### PR TITLE
Fix XSS vulnerability in todo workshop, fixes #517

### LINKED ISSUE #517: todo list allows arbitrary html in task
The todo workshop's main.js has this line in it:

```
span.innerHTML = description;
```

Did you really want to let the user add arbitrary HTML in the todo list? If you want the task input to be plain text, you can do this instead:

```
span.appendChild(document.createTextNode(description));
```

### PR DESCRIPTION
**Pull request by ad510**

### CODE REVIEW

**Comment by ad510** [comment]
Tests failed for the same reason as #451, but that should be fine.

**Comment by zachlatta** [comment]
Before this is merged I need to fix the tests. Things should never be merged into master unless the tests pass.

## 

Zach Latta
hackEDU| zach@hackedu.us

**Comment by ad510** [comment]
Also I need to fix some more issues mentioned in #517, so don't merge until I address those.

**Comment by zachlatta** [comment]
Sounds good!

On Sat, Aug 22, 2015 at 4:55 PM, Andrew Downing notifications@github.com
wrote:

> Also I need to fix some more issues mentioned in #517
> https://github.com/hackedu/hack-camp/issues/517, so don't merge until I
> address those.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/hackedu/hack-camp/pull/518#issuecomment-133766292.

## 

Zach Latta
hackEDU | zach@hackedu.us

**Comment by maxwofford** [comment]
@zachlatta I just merged #522. Is there a way to rerun these tests?

**Comment by zachlatta** [comment]
I can tell the CI directly to run the tests, but @ad510 needs to rebase master into this branch.

**Comment by ad510** [comment]
I could've finished this over the weekend instead of now, but better late than never, I guess. In particular, please look over the changes in messenger/README.md and todo/adding_tasks.md to make sure I explained things clearly enough.

**Comment by ad510** [comment]
Someone fixed the tests! Anyway I pulled from master and fixed the merge conflict.

**Comment by jonleung** [comment]
@ad510 looks good! Thanks for this!!

**Pull request merged**
