### PR TITLE
[demo activity] add details for putting instructions on whiteboard

### LINKED ISSUE #406: Include  demo instructions on the whiteboard
During demos, a list of things to be talked about (failures, what you built, etc.) should be on the whiteboard, along with guidelines for feedback for the hackers.

This should also be included in the playbook.

### PR DESCRIPTION
**Pull request by maxwofford**
@ssun098 How can this be improved?

I know I wasn't assigned to this, but I felt I could lay out the scaffold for it right now.

How everything feels at 5:30am -->

ps this closes #406

### CODE REVIEW

**Comment by maxwofford** [comment]
@zachlatta going to wait and have @ssun098 merge this, but would you please review it for the time being?

**Comment by selynna** [comment]
@MaxWofford I added some steps (things learned & feedback about positives/negatives), and rearranged the order, if that's okay.

**Comment by zachlatta** [comment]
@MaxWofford are you cool with @ssun098's changes? If so, can you squash the commits and merge this?

**Comment by maxwofford** [comment]
I'm good with the changes. Just squashed and merged. Thanks @ssun098 @zachlatta!

**Pull request merged**
