### PR TITLE
cohort 4: Add 'I have failed activity' guide

### PR DESCRIPTION
**Pull request by maxwofford**
@jonleung Is this missing anything?

cc/ @zachlatta

### CODE REVIEW

**Comment by maxwofford** [comment]
This addresses #222

**Comment by MaxWofford** [comment]
@jonleung Is this missing anything?

**Comment by maxwofford** [comment]
Wait, I forgot to add the applauding everyone's failure.

**Comment by maxwofford** [comment]
This would be a very different activity without applause.

**Comment by zachlatta** [comment]
LOL

**Comment by jonleung** [comment]
@MaxWofford 

Add:

That this activity is is good for
1) Enabling people to acknowledge their failures because they know that the response they will be met with support, not judgement
2) It gives everyone else an appropriate response when someone fails so they know what to do

The facilitators should explain why they are doing this activity

The facilitators should explain why failure is good (you are working at the bleeding edge of your ability). You should have ~equal parts failures and success. If you only have successes, you're doing things that are too easy. If you always, fail, you are doing things too hard.

The facilitator needs to know to encourage this to happen in the future. The facilitator should also talk about how this is a space that celebrates failure.

I would highly recommend a video to demonstrate this, otherwise the description is not clear.

Add that fact that they need to get everyone to applaud and cheer when someone shares their failure.

**Comment by zachlatta** [comment]
I agree with most of what you're saying, though I don't think we need a
video to communicate this.

## 

Zach Latta
Executive Director of hackEDU https://hackedu.us
http://zachlatta.com
https://github.com/zachlatta
https://twitter.com/zachlatta

**Comment by maxwofford** [comment]
@zachlatta Is this ready for merge?

**Comment by zachlatta** [comment]
Squashed and cherry picked into master in 8d0a59a094288857eb52c62079acf9fe97a9ec47.

**Pull request closed without merging**
