### PR TITLE
Fix grammar and content

### PR DESCRIPTION
**Pull request by selynna**
@jonleung

### CODE REVIEW

**Comment by zachlatta** [comment]
I'm happy to cherry-pick this and resolve any conflicts once @jonleung gives the green light.

**Comment by jonleung** [comment]
@zachlatta Looks good!

**Comment by jonleung** [comment]
@zachlatta looks good!

**Comment by zachlatta** [comment]
Cherry picked into the `distruption` branch in 4f9d8edc4fb1aa6fb77e1aab100b9dcce48d0292.

**Pull request closed without merging**
