### PR TITLE
Cohort 4: add intro talk

### PR DESCRIPTION
**Pull request by maxwofford**
_not ready for merge_

### CODE REVIEW

**Comment by maxwofford** [comment]
@zachlatta Would you please merge this when you wake up?
/cc @hackedu/hack-camp

**Comment by maxwofford** [comment]
This closes #283

**Comment by maxwofford** [comment]
This was checked over by @gemmabusoni.

**Comment by zachlatta** [comment]
:+1:

On Monday, August 3, 2015, Max Wofford notifications@github.com wrote:

> This was checked over by @gemmabusoni https://github.com/gemmabusoni.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/hackedu/hack-camp/pull/286#issuecomment-127263510.

## 

## 

Zach Latta
http://zachlatta.com
https://github.com/zachlatta
https://twitter.com/zachlatta

**Pull request merged**
