### PR TITLE
Shorten sfusd email blurb

### PR DESCRIPTION
**Pull request by maxwofford**
@zachlatta Could I get your eyes on this? I'm aiming for shorter and more to-the-point

### CODE REVIEW

**Comment by zachlatta** [comment]
Hmm, so I tried writing a couple revisions to this, but by far my favorite
is the email you sent with the subject "Hack Camp 2016".

What if we just use that as our base template? It's super good.

On Thu, May 19, 2016 at 6:05 PM, Max Wofford notifications@github.com
wrote:

> Assigned #627 https://github.com/hackclub/hackcamp/pull/627 to
> @zachlatta https://github.com/zachlatta.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/hackclub/hackcamp/pull/627#event-666582100

## 

Zach Latta
https://zachlatta.com http://zachlatta.com

**Comment by maxwofford** [comment]
As far as I can tell this is that email.

**Comment by zachlatta** [comment]
Here's the text I have for the mentioned email:

```
Hi NAME,

My name's Max Wofford and I work for Hack Club, a nonprofit based in San
Francisco that helps high schoolers start after-school coding clubs.

We're putting together a high school summer program, Hack Camp
(https://camp.hackclub.com), to teach first-time coders how to build websites
and games. I saw that you're the Computer Science teacher at HIGHSCHOOL and I'm
reaching out to ask for your help.

We've been getting too many experienced applicants and need help reaching
students where we can make the most impact – those who've never written any code
before. Could we get a short blurb about Hack Camp in the school bulletin? I've
attached it below:

--

Want to learn to build websites and games? Hack Camp is a two-week summer
program designed for high school students with little to no coding experience.
We'll bring you from your first line of code to publishing websites and making
your first games. It'll run in four two-week sessions throughout the summer.

For more info, check out https://camp.hackclub.com. Feel free to shoot me an
email at summer@hackclub.com!
```

**Comment by maxwofford** [comment]
@zachlatta: Ah, Ok. Just added it.

**Comment by zachlatta** [comment]
Did you forget to push? I don't see anything.

**Comment by maxwofford** [comment]
My bad. Not sure what happened there. Just amended

**Comment by zachlatta** [comment]
Can you fix conflicts? Then I'll merge.

On Thu, Jun 16, 2016 at 8:14 PM, Max Wofford notifications@github.com
wrote:

> My bad. Not sure what happened there. Just amended
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/hackclub/hackcamp/pull/627#issuecomment-226670684,
> or mute the thread
> https://github.com/notifications/unsubscribe/AA8j-M_v1FDwptRD3pVMyVX37iwIMmFmks5qMhEkgaJpZM4Iizhy
> .

## 

Zach Latta
https://zachlatta.com http://zachlatta.com

**Comment by maxwofford** [comment]
@ssun098 Would you mind taking this? @zachlatta is offline right now.

**Pull request merged**
