### PR TITLE
fixes #56 notes on galvanize agreement

### LINKED ISSUE #56: Create MOU with Galvanize for venue
Create a memo-of-understand with Galvanize and get both parties to sign it to confirm the venue in writing.

### PR DESCRIPTION
**Pull request by jonleung**
I wrote a document that summarizes what our agreement with Galvanize, fixes #56.

### CODE REVIEW

**Comment by zachlatta** [comment]
:+1:

Two quick things:
- This doesn't currently abide by our [Markdown guidelines](https://github.com/hackedu/meta/pull/76) (which still need to be merged). Specifically:
  -  it exceeds the 80 character line limit
  - `has *_already_* agreed` in the big heading should only use `_` for emphasis, not `*`
- Can you remove `fixes #56` from the commit message? If I merge this, #56 will be closed and this commit doesn't actually complete the issue.

**Comment by maxwofford** [comment]
@zachlatta, just curious-- would having `fixes #56` in the pr title auto-close the issue?

**Comment by zachlatta** [comment]
If I don't change the default commit message when merging, I think so.

recorded

**Comment by zachlatta** [comment]
Ping?

**Comment by maxwofford** [comment]
@zachlatta Reword the commit message (plz).

**Comment by zachlatta** [comment]
Done.

**Pull request merged**
