### PR TITLE
Add Howdy instructions to ACTIVITIES.md

### PR DESCRIPTION
**Pull request by maxwofford**

### CODE REVIEW

**Comment by maxwofford** [comment]
@ssun098^

**Comment by selynna** [comment]
I will get to it tonight, I already gave up on my 8 hours of sleep bc too
hard

**Comment by zachlatta** [comment]
...

you gotta follow through on the 8 hours if you want to see returns

On Tue, Jun 28, 2016 at 10:50 PM, Selynna Sun notifications@github.com
wrote:

> I will get to it tonight, I already gave up on my 8 hours of sleep bc too
> hard
> 
> On Tue, Jun 28, 2016 at 10:43 PM Max Wofford notifications@github.com
> wrote:
> 
> > @ssun098 https://github.com/ssun098^
> > 
> > —
> > You are receiving this because you were mentioned.
> > 
> > Reply to this email directly, view it on GitHub
> > https://github.com/hackclub/hackcamp/pull/702#issuecomment-229261969,
> > or mute the thread
> > <
> > https://github.com/notifications/unsubscribe/AHYhMk4b_ZRQNe0fWrutLo2TluMKnONpks5qQgYEgaJpZM4I_MHF
> > 
> > .
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> https://github.com/hackclub/hackcamp/pull/702#issuecomment-229262828,
> or mute the thread
> https://github.com/notifications/unsubscribe/AA8j-Ej5cYOOxkpuaCcNOeiEI_uV2B18ks5qQgeXgaJpZM4I_MHF
> .

## 

Zach Latta
Hack Club | zach@hackclub.com

**Comment by selynna** [comment]
I'm in a meeting though so I wouldn't be able to get 8 hours though

**Comment by selynna** [comment]
LOL I thought I was supposed to write documentation I didn't even realize
this was a pull request

**Comment by zachlatta** [comment]
you gotta schedule meetings to make time for those 8 hours

seriously, just pick a day and make it happen. you won't regret it. make it
this week.

On Tue, Jun 28, 2016 at 10:58 PM, Selynna Sun notifications@github.com
wrote:

> Merged #702 https://github.com/hackclub/hackcamp/pull/702.
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> https://github.com/hackclub/hackcamp/pull/702#event-707300263, or mute
> the thread
> https://github.com/notifications/unsubscribe/AA8j-IuPQ2wtcAFRqUKq0TDbk5nUG_2Bks5qQgmdgaJpZM4I_MHF
> .

## 

Zach Latta
https://zachlatta.com http://zachlatta.com

**Comment by selynna** [comment]
@saescapa has some nice time zone issues

**Pull request merged**
