### PR TITLE
Add 2016 session 3 day 1 shedule

### PR DESCRIPTION
**Pull request by maxwofford**

### CODE REVIEW

**Comment by selynna** [comment]
Fixed in #755, can we close this?

**Comment by maxwofford** [comment]
@ssun098 Yep!

**Comment by maxwofford** [comment]
Aw snap, I didn't properly review this before closing. Looks like #755 has different changes than this.

**Comment by maxwofford** [comment]
Cool! Now this is addressed by https://github.com/hackclub/camp/pull/755

**Pull request closed without merging**
