### PR TITLE
Patch 1

### PR DESCRIPTION
**Pull request by YafahEdelman**

### CODE REVIEW

**Comment by maxwofford** [comment]
@JacobEdelman Thanks so much for the PR!

**Comment by zachlatta** [comment]
@MaxWofford I'll take lead on cherry picking these over to master :-)

**Comment by zachlatta** [comment]
Cherry picked into master in bca1e2ffc13ef51b38b4c434b886eacaa7561f03.

**Comment by maxwofford** [comment]
@zachlatta The tests failed for the PR. Is there a way I can see the tests for `master`?

**Comment by zachlatta** [comment]
What if we just remove the tests for unrejector entirely? They seem to be
pretty flaky, especially considering they don't work for PRs made from a
fork, and they don't currently test much, besides the page loading at all.

On Mon, Aug 17, 2015 at 4:40 PM, Max Wofford notifications@github.com
wrote:

> @zachlatta https://github.com/zachlatta The tests failed for the PR. Is
> there a way I can see the tests for master?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/hackedu/hack-camp/pull/503#issuecomment-131995816.

## 

Zach Latta
hackEDU | zach@hackedu.us

**Comment by maxwofford** [comment]
@zachlatta Fine with that. We aren't doing anything with Hack Camp currently anyways. Can we take camp.hackedu.us down while we are at it?

**Comment by zachlatta** [comment]
Hmm, I don't know if it makes sense to take https://camp.hackedu.us down.
What if we just add a note to https://camp.hackedu.us saying it's over?

On Mon, Aug 17, 2015 at 5:31 PM, Max Wofford notifications@github.com
wrote:

> @zachlatta https://github.com/zachlatta Fine with that. We aren't doing
> anything with Hack Camp currently anyways. Can we take camp.hackedu.us
> down while we are at it?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/hackedu/hack-camp/pull/503#issuecomment-132004628.

## 

Zach Latta
hackEDU | zach@hackedu.us

**Pull request closed without merging**
