### PR TITLE
cohort 4: add energizers: one word radio, bad startup

### PR DESCRIPTION
**Pull request by maxwofford**

### CODE REVIEW

**Comment by maxwofford** [comment]
This closes #380 #382

**Comment by maxwofford** [comment]
It also includes a sharks and minnows activity for the hackers.

**Comment by maxwofford** [comment]
Would you please review this @zachlatta?

/cc @hackedu/hack-camp Anyone can check this out to merge it.

**Comment by zachlatta** [comment]
Cherry-picked into master in 6695213b0875a6355064f711a4729181f8c7d687.

**Pull request closed without merging**
