### PR TITLE
cohort 4: Add guidelines for project time in playbook/activities.md

### PR DESCRIPTION
**Pull request by maxwofford**
_not ready for merge_

### CODE REVIEW

**Comment by maxwofford** [comment]
@jonleung What is this missing?

**Comment by jonleung** [comment]
@MaxWofford, things to include
- [x] talk about the process for how the student should be driving this conversation, not the facillitator driving. "So what do you want to do now?" "Could you phrase that more specifically?"
- [x] make sure that the facillitator should be checking in with students actively and trying to spend as little time with a given student as possible. If there's a way for them to leave faster, do it. Some of this means getting a student to the point that they can work on a task on their own.
- [x] if you can have another student help this student, opt for that
- [x] don't correct things that they discovered on their own immediately otherwise they will think that everything that they discover is wrong. It's ok to have unoptimal code. Perhaps adding code review period is a good period to fix these errors, perhaps once at the end of each day.
- [x] make sure both partners are equally engaged, work on trying to diagnoes why if this is not the case
- [x] help them build the scooter (there is a description of building the scooter in the instagram workshop). (it seems like you've already included this)

Things to consider doing:
- [x] you could break this into multiple digestible sections with headings instead of a larger block of text (even though it's in bullet point form its a bit hard to figure out what the main points are)

just some things that I immediately thought of

EDIT by maxwofford: Added checkboxes to make it easier to keep track of what I've addressed.

**Comment by maxwofford** [comment]
@jonleung Thanks! I'll get on those.

**Comment by maxwofford** [comment]
@jonleung Is there a reason this was merged?

**Comment by maxwofford** [comment]
I'm reverting the merge for the time being and will ask someone to merge once all comments have been addressed.

**Comment by maxwofford** [comment]
Creating a new pull request: #253

**Comment by jonleung** [comment]
@MaxWofford oops lol

**Pull request merged**
