### PR TITLE
cohort 4: [workshop 3] add warnings that there are errors

### PR DESCRIPTION
**Pull request by jonleung**
Do not merge yet, still adding

### CODE REVIEW

**Comment by maxwofford** [comment]
@jonleung Is this ready for merge yet?

EDIT: If not, it might be worth it to close this.

**Comment by jonleung** [comment]
@MaxWofford, It's better with these changes than without them, let's merge it?

**Comment by zachlatta** [comment]
There are a ton of formatting changes in this PR. Perhaps split it up into
two commits and give the PR a more descriptive name?

On Mon, Aug 17, 2015 at 4:54 PM, Jonathan Leung notifications@github.com
wrote:

> @MaxWofford https://github.com/MaxWofford, It's better with these
> changes than without them, let's merge it?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/hackedu/hack-camp/pull/401#issuecomment-131997981.

## 

Zach Latta
hackEDU | zach@hackedu.us

**Comment by maxwofford** [comment]
@jonleung @zachlatta  I've broken the commit into 2 using `rebase` & `amend`. Turns out rebasing a branch on itself is a thing.



@jonleung If you ever want to learn about the magic of rewriting history, just ask. Git is legit shit.

**Pull request merged**
