### PR TITLE
Add energizers

### PR DESCRIPTION
**Pull request by maxwofford**
@zachlatta Is it okay to leave out the description of mafia for the time being?

### CODE REVIEW

**Comment by zachlatta** [comment]
Can these be linked to the schedule, where appropriate, as well?

On Wed, Aug 19, 2015 at 2:15 PM, Max Wofford notifications@github.com
wrote:

> Assigned #514 https://github.com/hackedu/hack-camp/pull/514 to
> @zachlatta https://github.com/zachlatta.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/hackedu/hack-camp/pull/514#event-387023026.

## 

Zach Latta
hackEDU | zach@hackedu.us

**Comment by maxwofford** [comment]
I will link to the schedule and close the energizer issues.

**Comment by maxwofford** [comment]
This closes #350
This closes #483
This closes #378

**Comment by maxwofford** [comment]
@zachlatta Could I please get your eyes on this?
This now adds both marshmallow tower and mafia energizers, as well as cleans up the SCHEDULE.

**Pull request merged**
