### PR TITLE
Added the Cohort 3 Day 5 Instagram Workshop!

### PR DESCRIPTION
**Pull request by jonleung**

### CODE REVIEW

**Comment by zachlatta** [comment]
Can you reword the commit to:

```
cohort 3: [workshops] add Instagram workshop
```

**Comment by maxwofford** [comment]
@jonleung Happy to merge this. If you need help rewording the commit, just ask!

`git commit --amend -m "cohort 3: [workshops] add Instagram workshop"`

**Comment by jonleung** [comment]
Finished writing workshop, blocking on PR @zachlatta 

https://github.com/hackedu/hack-camp/pull/183

**Comment by zachlatta** [comment]
Eh, I'll just go ahead and reword the commit for you.

**Comment by zachlatta** [comment]
Whoops! Accidentally closed the PR.

**Comment by jonleung** [comment]
I'm not sure what I'm supposed to be doing here?

**Comment by zachlatta** [comment]
Nothing. I rewrote the commit for you and merged it.

**Pull request merged**
